config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'high_voltage/pages#show', id: 'home'
  post "/vote", to: "votes#vote"
  resources :law_proposals

  get "/signup", to: "registrations#new", as: :signup_form
  post "/signup", to: "registrations#create", as: :signup
  get "/confirm/:token", to: "registrations#confirm", as: :confirm
  get "/login", to: "sessions#new", as: :login_form
  post "/login", to: "sessions#create", as: :login
  delete "/logout", to: "sessions#destroy", as: :logout

  namespace :admin do
    resources :law_proposals
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Votable

  validates :body, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/concerns/commentable.rb
# frozen_string_literal: true

module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable, dependent: :destroy
    has_many :users, through: :comments, source: :user
  end

  def add_comment(body: nil, user: nil)
    comments.create(body: body, user: user)
  end
end

app/models/concerns/votable.rb
# frozen_string_literal: true

module Votable
  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :votable, dependent: :destroy
    has_many :users, through: :votes, dependent: :destroy
  end

  def score
    votes.where(type: "upvote").count - votes.where(type: "downvote").count
  end

  def upvote!(user: nil)
    votes.create(type: "upvote", user: user)
  end

  def downvote!(user: nil)
    votes.create(type: "downvote", user: user)
  end
end

app/models/law_proposal.rb
# frozen_string_literal: true

class LawProposal < ApplicationRecord
  include Votable
  include Commentable

  validates :name, presence: true
  validates :url, presence: true, url: { allow_nil: true }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  has_secure_password
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  self.inheritance_column = nil

  enum type: {
    "upvote": "upvote",
    "downvote": "downvote"
  }

  validates :type, presence: true

  belongs_to :votable, polymorphic: true
  belongs_to :user
end

app/controllers/admin/law_proposals_controller.rb
# frozen_string_literal: true

module Admin
  class LawProposalsController < ::AdminController
    expose(:law_proposals) { LawProposal.all }
    expose(:law_proposal)

    def index
      authorize LawProposal
      policy_scope(LawProposal)
    end

    def show
      authorize law_proposal
    end

    def new
      authorize law_proposal
    end

    def create
      authorize law_proposal

      if law_proposal.save
        redirect_to admin_law_proposals_path
      else
        render :new
      end
    end

    def edit
      authorize law_proposal
    end

    def update
      authorize law_proposal

      if law_proposal.update(law_proposal_params)
        redirect_to admin_law_proposals_path
      else
        render :edit
      end
    end

    def destroy
      authorize law_proposal

      law_proposal.destroy
      redirect_to admin_law_proposals_path, status: :ok
    end

    private

    def law_proposal_params
      params.require(:law_proposal).permit(:name, :description, :url, :tags, :important_points)
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def policy_scope(scope)
    super([:admin, scope])
  end

  def authorize(record, query = nil)
    super([:admin, record], query)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pundit

  before_action :set_locale

  private

  def set_locale
    I18n.locale = extract_locale || params[:locale] || I18n.default_locale
  end

  def extract_locale
    tld = request.host.split(".").last
    I18n.available_locales.map(&:to_s).include?(tld) ? tld : nil
  end
end

app/controllers/law_proposals_controller.rb
# frozen_string_literal: true

class LawProposalsController < ApplicationController
  expose(:law_proposals) { LawProposal.all }
  expose(:law_proposal)

  def index; end

  def show; end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  expose(:user)

  def new; end

  def create
    if user.valid?
      user.confirmation_token = Digest::SHA256.hexdigest(Time.now.to_s)
      user.save
      RegistrationsMailer.send_confirmation_email(user).deliver
      redirect_to root_url, flash: { success: t(".confirmation_email_sent") }
    else
      render :new
    end
  end

  def confirm
    token = confirmation_params[:token]
    user = User.find_by(confirmation_token: token)
    if user && !user.confirmed_at
      user.confirmed_at = Time.now
      user.save
      redirect_to root_url, flash: { success: t(".confirmation_success") }
    else
      redirect_to root_url, flash: { error: t(".confirmation_failure") }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def confirmation_params
    params.permit(:token)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      log_in user
      redirect_to root_url, notice: t(".logged_in_successfully")
    else
      render :new, alert: t(".invalid_email_or_password")
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/votes_controller.rb
# frozen_string_literal: true

class VotesController < ApplicationController
  def vote
    result, votable = ProcessVote.new(
      votable_type: params[:type],
      id: params[:id],
      action: params[:user_action],
      user: current_user
    ).call

    case result
    when :success
      render json: { id: votable.id, score: votable.score }
    when :failure
      render json: { message: votable }, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Rails.application.routes.url_helpers

  def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-danger"
    when 'alert' then "alert alert-warning"
    end
  end

  def cancel_link(classes)
    link_to t('cancel_button'), request.env["HTTP_REFERER"],
            class: classes,
            confirm: t('confirm_canceling')
  end
end

app/helpers/law_proposals_helper.rb
# frozen_string_literal: true

module LawProposalsHelper
  def show_tags(law_proposal:)
    if law_proposal.tags.empty?
      I18n.t("helpers.law_proposals.no_tags")
    else
      law_proposal.tags.join(", ")
    end
  end
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/views/admin/law_proposals/_form.html.haml
- form_class = "space-y-4"
- label_class = "block mb-1"
- input_class = "w-full h-10 px-3 text-base placeholder-gray-600 border rounded-lg focus:shadow-outline"
- select_class = "w-full h-10 pl-3 pr-6 text-base placeholder-gray-600 border rounded-lg appearance-none focus:shadow-outline"
- default_select_option = I18n.t("admin.law_proposals.form.select_area") 
- cities = [default_select_option, "Waraszawa", "Wrocław"]
- select_collection = cities.zip(cities)
- select_options = options_from_collection_for_select(select_collection, 'first', 'last', { selected: default_select_option, disabled: default_select_option })

= form_for [:admin, law_proposal] do |f|
  = f.label :name, class: label_class
  = f.text_field :name, class: input_class

  = f.label :description, class: label_class
  = f.text_field :description, class: input_class

  = f.label :url, class: label_class
  = f.text_field :url, class: input_class

  = f.label :important_points, class: label_class
  = f.text_field :important_points, class: input_class

  = f.label :tags, class: label_class
  = f.text_field :tags, class: input_class

  = f.label :area, class: label_class
  .relative.inline-block.w-full
    = f.text_field :area, class: input_class, required: true, list: "area-list", placeholder: default_select_option
    %datalist#area-list
      = select_options
    .absolute.inset-y-0.right-0.flex.items-center.px-2.pointer-events-none
      %svg.w-4.h-4.fill-current{:viewbox => "0 0 20 20"}
        %path{"clip-rule" => "evenodd", :d => "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z", "fill-rule" => "evenodd"}

  = f.submit t(".save"), class: "mdc-button mdc-button--raised mt-3"
  = cancel_link("mdc-button mt-3")

app/views/admin/law_proposals/edit.html.haml
.mdc-card.mdc-elevation--z12
  .card-content
    .row
      .col
        %h1= t(".header")

    = render "form"

app/views/admin/law_proposals/index.html.haml
- th_class = "p-3 font-bold uppercase bg-primary text-white border border-gray-300 hidden lg:table-cell"
- first_td_class = "w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static"
- subsequent_td_class = "w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static"
- span_class = "lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase"

.container.mx-auto.flex.flex-col.flex-wrap
  %h2.lg:my-8= t(".header")

  .buttons.lg:mb-4
    = link_to t(".create"), new_admin_law_proposal_url, class: "btn-primary rounded flex-grow-0 w-20"

  %table.border-collapse.shadow-lg.w-full
    %thead
      %tr
        %th{class: th_class} ID
        %th{class: th_class}= LawProposal.human_attribute_name(:name)
        %th{class: th_class}= LawProposal.human_attribute_name(:description)
        %th{class: th_class}= LawProposal.human_attribute_name(:url)
        %th{class: th_class}= t(".actions")
    %tbody
      - law_proposals.each do |law_proposal|
        %tr(class="bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0")
          %td{class: first_td_class}
            %span{class: span_class} ID
            = law_proposal.id
          %td{class: subsequent_td_class}
            %span{class: span_class}= LawProposal.human_attribute_name(:name)
            = law_proposal.name
          %td{class: subsequent_td_class}
            %span{class: span_class}= LawProposal.human_attribute_name(:description)
            = law_proposal.description
          %td{class: subsequent_td_class}
            %span{class: span_class}= LawProposal.human_attribute_name(:url)
            = link_to law_proposal.url, law_proposal.url
          %td{class: subsequent_td_class}
            %span{class: span_class}= t(".actions")
            = link_to t(".show"), admin_law_proposal_url(law_proposal)
            = link_to t(".edit"), edit_admin_law_proposal_url(law_proposal)
            = link_to t(".delete"), admin_law_proposal_url(law_proposal), method: :delete, data: { confirm: "Czy na pewno chcesz usunąć #{law_proposal.name}?" }

app/views/admin/law_proposals/new.html.haml
.container.mx-auto.flex.flex-col.flex-wrap
  %h2.lg:my-8= t(".header")
  = render "form"

app/views/admin/law_proposals/show.html.haml
.mdc-card.mdc-elevation--z12
  .card-content
    .row
      .col
        %h1 #{LawProposal.human_attribute_name(:name)}
        %p #{law_proposal.name}
        %h1 #{LawProposal.human_attribute_name(:description)}
        %p #{law_proposal.description}
        %h1 #{LawProposal.human_attribute_name(:important_points)}
        %p #{law_proposal.important_points}
        %h1 #{LawProposal.human_attribute_name(:tags)}
        %p #{show_tags(law_proposal: law_proposal)}
        %h1 #{t(".source")}
        %p #{link_to law_proposal.url, law_proposal.url}

app/views/law_proposals/index.html.haml
- tr_class = "bg-white lg:hover:bg-gray-100 flex lg:table-row flex-row lg:flex-row flex-wrap lg:flex-no-wrap mb-10 lg:mb-0"
- th_class = "p-3 font-bold uppercase bg-primary text-white border border-gray-300 hidden lg:table-cell"
- first_td_class = "w-full lg:w-auto p-3 text-gray-800 text-center border border-b block lg:table-cell relative lg:static"
- subsequent_td_class = "w-full lg:w-auto p-3 text-gray-800 text-center border border-b text-center block lg:table-cell relative lg:static"
- span_class = "lg:hidden absolute top-0 left-0 bg-blue-200 px-2 py-1 text-xs font-bold uppercase"

.container.mx-auto.flex.flex-col.flex-wrap
  %h2.lg:my-8= t(".header")

  %table.border-collapse.shadow-lg.w-full
    %thead
      %tr
        %th{class: th_class} Wynik
        %th{class: th_class}= LawProposal.human_attribute_name(:name)
        %th{class: th_class}= LawProposal.human_attribute_name(:description)
        %th{class: th_class}= LawProposal.human_attribute_name(:url)
        %th{class: th_class}= t(".actions")
    %tbody
      - law_proposals.each do |law_proposal|
        %tr{class: tr_class, data: { controller: "votable", target: "votable.item", "votable-type": law_proposal.class.to_s, "votable-id": law_proposal.id, "votable-score": law_proposal.score } }
          %td{class: first_td_class}
            %span{class: span_class} Wynik
            .score= law_proposal.score
          %td{class: subsequent_td_class}
            %span{class: span_class}= LawProposal.human_attribute_name(:name)
            = law_proposal.name
          %td{class: subsequent_td_class}
            %span{class: span_class}= LawProposal.human_attribute_name(:description)
            = law_proposal.description
          %td{class: subsequent_td_class}
            %span{class: span_class}= LawProposal.human_attribute_name(:url)
            = link_to law_proposal.url, law_proposal.url
          %td{class: subsequent_td_class}
            %span{class: span_class}= t(".actions")
            %span{data: { action: "click->votable#upvote"} } 👍
            %span{data: { action: "click->votable#removeVote"} } ✋
            %span{data: { action: "click->votable#downvote"} } 👎

app/views/law_proposals/show.html.haml
.mdc-card.mdc-elevation--z12
  .card-content
    .row
      .col
        %h1.mdc-typography--headline1= law_proposal.name
        %p
          #{t(".source")}: #{link_to law_proposal.url}
        .mdc-list-divider{role: "separator"}
        %ul.mdc-list.mdc-list--two-line.mcd-list--avatar-list
          - law_proposal.comments.each do |comment|
            %li.mdc-list-item{data: { controller: "votable", target: "votable.item", "votable-type": comment.class.to_s, "votable-id": comment.id, "votable-score": comment.score } }
              %span.mdc-list-item__graphic= comment.score
              %span.mdc-list-item__text
                %span.mdc-list-item__primary-text= comment.body
              %span.mdc-list-item__meta.voting-buttons
                %span.material-icons.md-48{data: { action: "click->votable#upvote"} } arrow_drop_up
                %span.material-icons.md-48{data: { action: "click->votable#downvote"} } arrow_drop_down
            %li.mdc-list-divider{role: "separator"}

app/views/layouts/application.html.haml
!!!
%html.h-screen
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %title Polikompas
    %link{href: "https://rsms.me/inter/inter.css", rel: "stylesheet"}
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_packs_with_chunks_tag 'stylesheets', media: 'all', 'data-turbolinks-track': 'reload'
  %body.h-full
    .flex.flex-col.h-full
      = render "shared/navigation"
      = yield

app/views/pages/home.html.haml
.flex.flex-col.h-full
  .call-to-action.flex-grow.flex.flex-col.justify-center.items-center.h-full.flex-shrink-0
    %h1.text-white.font-semibold Konsultacje Obywatelskie
    %h2.text-white.font-thin.sm:font-normal.md:font-thin
      Niech politycy znają
      %span.text-primary Twoje zdanie
    .inline-flex.mt-6
      %a.inline-block.btn-primary.rounded{href: "#"} Zaloguj się
      %span.text-white.mx-4.self-center lub
      %a.inline-block.btn-primary.rounded{href: "#"} Zarejestruj się
    .inline-flex.mt-6
      %h1.text-white.font-semibold Nie wiesz o chodzi?
    .inline-flex.mt-6
      .modal.opacity-0.pointer-events-none.fixed.w-full.h-full.top-0.left-0.flex.items-center.justify-center
        .modal-overlay.absolute.w-full.h-full.bg-gray-900.opacity-50
        .modal-container.bg-white.max-w-full.mx-auto.rounded.shadow-lg.z-50.overflow-y-auto{:class => "w-6/12"}
          .modal-content.py-4.text-left.px-6
            .flex.justify-between.items-center.pb-3
              %p.font-bold Czym są Konsultacje Obywatelskie?
              .modal-close.cursor-pointer.z-50
                %svg.fill-current.text-black{:height => "18", :viewbox => "0 0 18 18", :width => "18", :xmlns => "http://www.w3.org/2000/svg"}
                  %path{:d => "M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"}
            %video#introduction-video{poster: asset_pack_path("media/images/intro.png")}(controls width="100%")
              %source{src: asset_pack_path("media/videos/intro.webm")}(type="video/webm")
            .flex.justify-end.pt-2
              %button.modal-close.btn-primary.rounded Zamknij
      %button.video-modal.modal-open.btn-primary.rounded Obejrzyj filmik

app/views/shared/_form_card.html.haml
.card
  .card-body
    = yield

app/views/shared/_navigation.html.erb
<nav x-data="{ open: false }" @keydown.window.escape="open = false" class="bg-primary">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <h3 class="text-white text-lg">
              <%= link_to "Polikompas", root_url %>
            </h3>
          </div>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline">
              <%= link_to t(".law_proposals"), law_proposals_path, class: "menu-link" %>
              <%= link_to t(".privacy_policy"), page_path("privacy"), class: "menu-link" %>
              <% if policy([:admin, LawProposal]).index? %>
                <%= link_to t(".manage_law_proposals"), admin_law_proposals_url, class: "menu-link" %>
              <%end %>
            </div>
          </div>
        </div>
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <button class="p-1 border-2 border-transparent text-primary rounded-full hover:text-white focus:outline-none focus:text-white focus:bg-gray-700">
              <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
              </svg>
            </button>
            <div @click.away="open = false" class="ml-3 relative" x-data="{ open: false }">
              <div>
                <button @click="open = !open" class="max-w-xs flex items-center text-sm rounded-full text-white focus:outline-none focus:shadow-solid">
                  <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
                </button>
              </div>
              <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg">
                <div class="py-1 rounded-md bg-white shadow-xs">
                  <%= link_to t(".logout"), logout_path, method: :delete, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="-mr-2 flex md:hidden">
          <button @click="open = !open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:bg-gray-700 focus:text-white">
            <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
              <path :class="{'hidden': open, 'inline-flex': !open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
              <path :class="{'hidden': !open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
      </div>
    </div>
    <div :class="{'block': open, 'hidden': !open}" class="hidden md:hidden">
      <div class="px-2 pt-2 pb-3 sm:px-3">
        <%= link_to t(".law_proposals"), law_proposals_path, class: "mt-1 block px-3 py-2 rounded-md text-base font-medium text-white hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" %>
        <%= link_to t(".privacy_policy"), page_path("privacy"), class: "mt-1 block px-3 py-2 rounded-md text-base font-medium text-white hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" %>
      </div>
      <div class="pt-4 pb-3 border-t border-gray-700">
        <div class="flex items-center px-5">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
          </div>
          <div class="ml-3">
            <div class="text-base font-medium leading-none text-white">Tom Cook</div>
            <div class="mt-1 text-sm font-medium leading-none text-gray-400">tom@example.com</div>
          </div>
        </div>
        <div class="mt-3 px-2">
          <%= link_to t(".logout"), logout_path, method: :delete, class: "mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700" %>
        </div>
      </div>
    </div>
  </nav>